// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using WebApiExample.Models;

namespace WebApiExample.Data
{
    public partial interface ITestDataBaseContextProcedures
    {
        Task<List<SpGetUsuariosResult>> SpGetUsuariosAsync(string IdUsuario, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
